Test SonarQube

diff --git a/.github/workflows/customer-ci.yaml b/.github/workflows/customer-ci.yaml
--- a/.github/workflows/customer-ci.yaml
+++ b/.github/workflows/customer-ci.yaml
@@ -39,37 +39,42 @@ jobs:
         with:
           sarif_file: snyk.sarif
 
-#   Build:
-#     runs-on: ubuntu-latest
-#     env:
-#       FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
-#     steps:
-#       - uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-#       - uses: ./.github/workflows/actions
-#       - name: Run Maven Build Command
-#         run: mvn clean install -pl customer -am
-#       - name: Run Maven Checkstyle
-#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-#         run: mvn checkstyle:checkstyle -pl customer -am -Dcheckstyle.output.file=customer-checkstyle-result.xml
-#       - name: Upload Checkstyle Result
-#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-#         uses: jwgmeligmeyling/checkstyle-github-action@master
-#         with:
-#           path: '**/customer-checkstyle-result.xml'
-#       - name: Test Results
-#         uses: dorny/test-reporter@v1
-#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
-#         with:
-#           name: Customer-Service-Unit-Test-Results
-#           path: "customer/**/*-reports/TEST*.xml"
-#           reporter: java-junit
-#       - name: Analyze with sonar cloud
-#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-#         env:
-#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#         run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f customer
+      - name: Analyze with sonar cloud
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f customer
+
+      #   Build:
+      #     runs-on: ubuntu-latest
+      #     env:
+      #       FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
+      #     steps:
+      #       - uses: actions/checkout@v4
+      #         with:
+      #           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      #       - uses: ./.github/workflows/actions
+      #       - name: Run Maven Build Command
+      #         run: mvn clean install -pl customer -am
+      #       - name: Run Maven Checkstyle
+      #         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #         run: mvn checkstyle:checkstyle -pl customer -am -Dcheckstyle.output.file=customer-checkstyle-result.xml
+      #       - name: Upload Checkstyle Result
+      #         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #         uses: jwgmeligmeyling/checkstyle-github-action@master
+      #         with:
+      #           path: '**/customer-checkstyle-result.xml'
+      #       - name: Test Results
+      #         uses: dorny/test-reporter@v1
+      #         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+      #         with:
+      #           name: Customer-Service-Unit-Test-Results
+      #           path: "customer/**/*-reports/TEST*.xml"
+      #           reporter: java-junit
+      - name: Analyze with sonar cloud
+        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f customer
 #       - name: OWASP Dependency Check
 #         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
 #         uses: dependency-check/Dependency-Check_Action@main
