ci workflow for media service

diff --git a/.github/workflows/media-ci.yaml b/.github/workflows/media-ci.yaml
--- a/.github/workflows/media-ci.yaml
+++ b/.github/workflows/media-ci.yaml
@@ -1,90 +1,155 @@
+# name: media service ci
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#     paths:
+#       - "media/**"
+#       - ".github/workflows/actions/action.yaml"
+#       - ".github/workflows/media-ci.yaml"
+#       - "pom.xml"
+#   pull_request:
+#     branches: [ "main" ]
+#     paths:
+#       - "media/**"
+#       - ".github/workflows/actions/action.yaml"
+#       - ".github/workflows/media-ci.yaml"
+#       - "pom.xml"
+#   workflow_dispatch:
+
+# jobs:
+#   Build:
+#     runs-on: ubuntu-latest
+#     env:
+#       FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
+#     steps:
+#       - uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+#       - uses: ./.github/workflows/actions
+#       - name: Run Maven Build Command
+#         run: mvn clean install -pl media -am
+#       - name: Run Maven Checkstyle
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         run: mvn checkstyle:checkstyle -pl media -am -Dcheckstyle.output.file=media-checkstyle-result.xml
+#       - name: Upload Checkstyle Result
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: jwgmeligmeyling/checkstyle-github-action@master
+#         with:
+#           path: '**/media-checkstyle-result.xml'
+#       - name: Test Results
+#         uses: dorny/test-reporter@v1
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+#         with:
+#           name: Media-Service-Unit-Test-Results
+#           path: "media/**/*-reports/TEST*.xml"
+#           reporter: java-junit
+#       - name: Analyze with sonar cloud
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         env:
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f media
+#       - name: OWASP Dependency Check
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: dependency-check/Dependency-Check_Action@main
+#         env:
+#           JAVA_HOME: /opt/jdk
+#         with:
+#           project: 'yas'
+#           path: '.'
+#           format: 'HTML'
+#       - name: Upload OWASP Dependency Check results
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: actions/upload-artifact@master
+#         with:
+#           name: OWASP Dependency Check Report
+#           path: ${{github.workspace}}/reports
+#       - name: Add coverage report to PR
+#         uses: madrapps/jacoco-report@v1.6.1
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         with:
+#           paths: ${{github.workspace}}/media/target/site/jacoco/jacoco.xml
+#           token: ${{secrets.GITHUB_TOKEN}}
+#           min-coverage-overall: 80
+#           min-coverage-changed-files: 60
+#           title: 'Media Coverage Report'
+#           update-comment: true
+#       - name: Log in to the Container registry
+#         if: ${{ github.ref == 'refs/heads/main' }}
+#         uses: docker/login-action@v3
+#         with:
+#           registry: ghcr.io
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Build and push Docker images
+#         if: ${{ github.ref == 'refs/heads/main' }}
+#         uses: docker/build-push-action@v6
+#         with:
+#           context: ./media
+#           push: true
+#           tags: ghcr.io/nashtech-garage/yas-media:latest
+
 name: media service ci
 
 on:
-  push:
-    branches: [ "main" ]
-    paths:
-      - "media/**"
-      - ".github/workflows/actions/action.yaml"
-      - ".github/workflows/media-ci.yaml"
-      - "pom.xml"
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
     paths:
       - "media/**"
       - ".github/workflows/actions/action.yaml"
       - ".github/workflows/media-ci.yaml"
       - "pom.xml"
-  workflow_dispatch:
 
 jobs:
-  Build:
+  build-test-analyze:
+    name: Build, Test, Snyk & SonarQube
     runs-on: ubuntu-latest
     env:
       FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - uses: ./.github/workflows/actions
-      - name: Run Maven Build Command
-        run: mvn clean install -pl media -am
-      - name: Run Maven Checkstyle
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        run: mvn checkstyle:checkstyle -pl media -am -Dcheckstyle.output.file=media-checkstyle-result.xml
-      - name: Upload Checkstyle Result
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: jwgmeligmeyling/checkstyle-github-action@master
+          fetch-depth: 0 # for SonarQube
+
+      - name: Set up java
+        uses: actions/setup-java@v4
         with:
-          path: '**/media-checkstyle-result.xml'
-      - name: Test Results
-        uses: dorny/test-reporter@v1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
-        with:
-          name: Media-Service-Unit-Test-Results
-          path: "media/**/*-reports/TEST*.xml"
-          reporter: java-junit
-      - name: Analyze with sonar cloud
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+          distribution: 'temurin'
+          java-version: '21'
+          cache: 'maven'
+
+      # snyk scan
+      - name: Snyk security scan
+        uses: snyk/actions/maven@master
         env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          args: --file=media/pom.xml --severity-threshold=high
+
+      # build, test and sonar scan
+      - name: Build, test and analyze
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f media
-      - name: OWASP Dependency Check
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: dependency-check/Dependency-Check_Action@main
-        env:
-          JAVA_HOME: /opt/jdk
+        run: >
+          mvn -f media/pom.xml clean verify 
+          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
+          -Dsonar.projectKey=thanhdatttt_DevOps-Project
+          -Dsonar.organization=thanhdatttt 
+          -Dsonar.host.url=https://sonarcloud.io 
+          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
+
+      - name: Upload Test Results
+        uses: actions/upload-artifact@v4
+        if: always()
         with:
-          project: 'yas'
-          path: '.'
-          format: 'HTML'
-      - name: Upload OWASP Dependency Check results
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: actions/upload-artifact@master
+          name: media-test-results
+          path: media/target/surefire-reports/
+
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v4
+        if: always()
         with:
-          name: OWASP Dependency Check Report
-          path: ${{github.workspace}}/reports
-      - name: Add coverage report to PR
-        uses: madrapps/jacoco-report@v1.6.1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        with:
-          paths: ${{github.workspace}}/media/target/site/jacoco/jacoco.xml
-          token: ${{secrets.GITHUB_TOKEN}}
-          min-coverage-overall: 80
-          min-coverage-changed-files: 60
-          title: 'Media Coverage Report'
-          update-comment: true
-      - name: Log in to the Container registry
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build and push Docker images
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: ./media
-          push: true
-          tags: ghcr.io/nashtech-garage/yas-media:latest
+          name: media-coverage-report
+          path: media/target/site/jacoco/
