update ci for media and product service

diff --git a/.github/workflows/product-ci.yaml b/.github/workflows/product-ci.yaml
--- a/.github/workflows/product-ci.yaml
+++ b/.github/workflows/product-ci.yaml
@@ -1,90 +1,165 @@
+# name: product service ci
+
+# on:
+#   push:
+#     branches: [ "main" ]
+#     paths:
+#       - "product/**"
+#       - ".github/workflows/actions/action.yaml"
+#       - ".github/workflows/product-ci.yaml"
+#       - "pom.xml"
+#   pull_request:
+#     branches: [ "main" ]
+#     paths:
+#       - "product/**"
+#       - ".github/workflows/actions/action.yaml"
+#       - ".github/workflows/product-ci.yaml"
+#       - "pom.xml"
+#   workflow_dispatch:
+
+# jobs:
+#   Build:
+#     runs-on: ubuntu-latest
+#     env:
+#       FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
+#     steps:
+#       - uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+#       - uses: ./.github/workflows/actions
+#       - name: Run Maven Build Command
+#         run: mvn clean install -pl product -am
+#       - name: Run Maven Checkstyle
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         run: mvn checkstyle:checkstyle -pl product -am -Dcheckstyle.output.file=product-checkstyle-result.xml
+#       - name: Upload Checkstyle Result
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: jwgmeligmeyling/checkstyle-github-action@master
+#         with:
+#           path: '**/product-checkstyle-result.xml'
+#       - name: Test Results
+#         uses: dorny/test-reporter@v1
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+#         with:
+#           name: Product-Service-Unit-Test-Results
+#           path: "product/**/*-reports/TEST*.xml"
+#           reporter: java-junit
+#       - name: Analyze with sonar cloud
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         env:
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f product
+#       - name: OWASP Dependency Check
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: dependency-check/Dependency-Check_Action@main
+#         env:
+#           JAVA_HOME: /opt/jdk
+#         with:
+#           project: 'yas'
+#           path: '.'
+#           format: 'HTML'
+#       - name: Upload OWASP Dependency Check results
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         uses: actions/upload-artifact@master
+#         with:
+#           name: OWASP Dependency Check Report
+#           path: ${{github.workspace}}/reports
+#       - name: Add coverage report to PR
+#         uses: madrapps/jacoco-report@v1.6.1
+#         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+#         with:
+#           paths: ${{github.workspace}}/product/target/site/jacoco/jacoco.xml
+#           token: ${{secrets.GITHUB_TOKEN}}
+#           min-coverage-overall: 80
+#           min-coverage-changed-files: 60
+#           title: 'Product Coverage Report'
+#           update-comment: true
+#       - name: Log in to the Container registry
+#         if: ${{ github.ref == 'refs/heads/main' }}
+#         uses: docker/login-action@v3
+#         with:
+#           registry: ghcr.io
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Build and push Docker images
+#         if: ${{ github.ref == 'refs/heads/main' }}
+#         uses: docker/build-push-action@v6
+#         with:
+#           context: ./product
+#           push: true
+#           tags: ghcr.io/nashtech-garage/yas-product:latest
 name: product service ci
 
 on:
   push:
     branches: [ "main" ]
     paths:
-      - "product/**"
+      - 'product/**'
       - ".github/workflows/actions/action.yaml"
       - ".github/workflows/product-ci.yaml"
       - "pom.xml"
   pull_request:
-    branches: [ "main" ]
     paths:
       - "product/**"
       - ".github/workflows/actions/action.yaml"
       - ".github/workflows/product-ci.yaml"
       - "pom.xml"
-  workflow_dispatch:
 
 jobs:
-  Build:
+  build-test-analyze:
+    name: Build, Test, Snyk & SonarQube
     runs-on: ubuntu-latest
-    env:
-      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout source code
+        uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - uses: ./.github/workflows/actions
-      - name: Run Maven Build Command
-        run: mvn clean install -pl product -am
-      - name: Run Maven Checkstyle
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        run: mvn checkstyle:checkstyle -pl product -am -Dcheckstyle.output.file=product-checkstyle-result.xml
-      - name: Upload Checkstyle Result
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: jwgmeligmeyling/checkstyle-github-action@master
+          fetch-depth: 0 # for SonarQube
+
+      - name: Set up java and jdk21
+        uses: actions/setup-java@v4
         with:
-          path: '**/product-checkstyle-result.xml'
-      - name: Test Results
-        uses: dorny/test-reporter@v1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
-        with:
-          name: Product-Service-Unit-Test-Results
-          path: "product/**/*-reports/TEST*.xml"
-          reporter: java-junit
-      - name: Analyze with sonar cloud
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+          distribution: 'temurin'
+          java-version: '21'
+          cache: 'maven'
+
+      # snyk scan
+      - name: Snyk security scan
+        uses: snyk/actions/maven@master
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f product
-      - name: OWASP Dependency Check
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: dependency-check/Dependency-Check_Action@main
-        env:
-          JAVA_HOME: /opt/jdk
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
-          project: 'yas'
-          path: '.'
-          format: 'HTML'
-      - name: Upload OWASP Dependency Check results
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: actions/upload-artifact@master
+          args: --file=product/pom.xml --severity-threshold=high
+
+      # test
+      - name: Test and coverage
+        run: mvn clean test jacoco:report
+        # env:
+        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        # run: >
+        #   mvn -f product/pom.xml clean verify 
+        #   org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
+        #   -Dsonar.projectKey=thanhdatttt_DevOps-Project
+        #   -Dsonar.organization=thanhdatttt 
+        #   -Dsonar.host.url=https://sonarcloud.io 
+        #   -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
+
+      # test results
+      - name: Upload test results
+        uses: actions/upload-artifact@v4
+        if: always()
         with:
-          name: OWASP Dependency Check Report
-          path: ${{github.workspace}}/reports
-      - name: Add coverage report to PR
-        uses: madrapps/jacoco-report@v1.6.1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+          name: product-test-results
+          path: product/target/surefire-reports/
+
+      # coverage report
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v4
+        if: always()
         with:
-          paths: ${{github.workspace}}/product/target/site/jacoco/jacoco.xml
-          token: ${{secrets.GITHUB_TOKEN}}
-          min-coverage-overall: 80
-          min-coverage-changed-files: 60
-          title: 'Product Coverage Report'
-          update-comment: true
-      - name: Log in to the Container registry
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build and push Docker images
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: ./product
-          push: true
-          tags: ghcr.io/nashtech-garage/yas-product:latest
+          name: product-coverage-report
+          path: product/target/site/jacoco/
+
+      #build
+      - name: Build
+        run: mvn package -DskipTests
