Update promotion-ci.yaml

diff --git a/.github/workflows/promotion-ci.yaml b/.github/workflows/promotion-ci.yaml
--- a/.github/workflows/promotion-ci.yaml
+++ b/.github/workflows/promotion-ci.yaml
@@ -26,65 +26,89 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
-      - uses: ./.github/workflows/actions
-      - name: Run Maven Build Command
-        run: mvn clean install -pl promotion -am
-      - name: Run Maven Checkstyle
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        run: mvn checkstyle:checkstyle -pl promotion -am -Dcheckstyle.output.file=promotion-checkstyle-result.xml
-      - name: Upload Checkstyle Result
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: jwgmeligmeyling/checkstyle-github-action@master
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/maven@master
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
-          path: '**/promotion-checkstyle-result.xml'
-      - name: Test Results
-        uses: dorny/test-reporter@v1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+          args: --sarif-file-output=snyk.sarif
+
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v3
         with:
-          name: Promotion-Service-Unit-Test-Results
-          path: "promotion/**/*-reports/TEST*.xml"
-          reporter: java-junit
+          sarif_file: snyk.sarif
+
+      - name: Install core project with Maven
+        run: |
+          mvn clean package
+          mvn -B -X install --file pom.xml
+          mvn compile
+          mvn -B package --file pom.xml
       - name: Analyze with sonar cloud
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f promotion
-      - name: OWASP Dependency Check
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: dependency-check/Dependency-Check_Action@main
-        env:
-          JAVA_HOME: /opt/jdk
-        with:
-          project: 'yas'
-          path: '.'
-          format: 'HTML'
-      - name: Upload OWASP Dependency Check results
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        uses: actions/upload-artifact@master
-        with:
-          name: OWASP Dependency Check Report
-          path: ${{github.workspace}}/reports
-      - name: Add coverage report to PR
-        uses: madrapps/jacoco-report@v1.6.1
-        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-        with:
-          paths: ${{github.workspace}}/promotion/target/site/jacoco/jacoco.xml
-          token: ${{secrets.GITHUB_TOKEN}}
-          min-coverage-overall: 80
-          min-coverage-changed-files: 60
-          title: 'Promotion Coverage Report'
-          update-comment: true
-      - name: Log in to the Container registry
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Build and push Docker images
-        if: ${{ github.ref == 'refs/heads/main' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: ./promotion
-          push: true
-          tags: ghcr.io/nashtech-garage/yas-promotion:latest
+        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f customer
+      # - uses: ./.github/workflows/actions
+      # - name: Run Maven Build Command
+      #   run: mvn clean install -pl promotion -am
+      # - name: Run Maven Checkstyle
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   run: mvn checkstyle:checkstyle -pl promotion -am -Dcheckstyle.output.file=promotion-checkstyle-result.xml
+      # - name: Upload Checkstyle Result
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   uses: jwgmeligmeyling/checkstyle-github-action@master
+      #   with:
+      #     path: '**/promotion-checkstyle-result.xml'
+      # - name: Test Results
+      #   uses: dorny/test-reporter@v1
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
+      #   with:
+      #     name: Promotion-Service-Unit-Test-Results
+      #     path: "promotion/**/*-reports/TEST*.xml"
+      #     reporter: java-junit
+      # - name: Analyze with sonar cloud
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #   run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f promotion
+      # - name: OWASP Dependency Check
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   uses: dependency-check/Dependency-Check_Action@main
+      #   env:
+      #     JAVA_HOME: /opt/jdk
+      #   with:
+      #     project: 'yas'
+      #     path: '.'
+      #     format: 'HTML'
+      # - name: Upload OWASP Dependency Check results
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   uses: actions/upload-artifact@master
+      #   with:
+      #     name: OWASP Dependency Check Report
+      #     path: ${{github.workspace}}/reports
+      # - name: Add coverage report to PR
+      #   uses: madrapps/jacoco-report@v1.6.1
+      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+      #   with:
+      #     paths: ${{github.workspace}}/promotion/target/site/jacoco/jacoco.xml
+      #     token: ${{secrets.GITHUB_TOKEN}}
+      #     min-coverage-overall: 80
+      #     min-coverage-changed-files: 60
+      #     title: 'Promotion Coverage Report'
+      #     update-comment: true
+      # - name: Log in to the Container registry
+      #   if: ${{ github.ref == 'refs/heads/main' }}
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Build and push Docker images
+      #   if: ${{ github.ref == 'refs/heads/main' }}
+      #   uses: docker/build-push-action@v6
+      #   with:
+      #     context: ./promotion
+      #     push: true
+      #     tags: ghcr.io/nashtech-garage/yas-promotion:latest
